services:
  trendvid:
    build: .
    container_name: trendvid
    working_dir: /app
    volumes:
      - ./:/app
    command:
      - --text
      - "ĞŸÑ€Ğ¸Ğ²Ñ–Ñ‚! Ğ¦Ğµ Docker Ñ‚ĞµÑÑ‚ ğŸš€"
      - --bg
      - "/app/assets/video/subway.mp4"
      - --out
      - "/app/.output/out.mp4"
      - --voice
      - "uk-UA-PolinaNeural"
